apiVersion: v1
kind: Service
metadata:
  name: {{ include "electricity.fullname" . }}
  labels:
    app.kubernetes.io/name: electricity-price
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: electricity-price
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP

