---
image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v0.1.6
  digest: "sha256:f96dec7a8aa1d7f5e5b5cf71e03a1ee9b87e04c559af3e3c36fe373e14275d93"
resources:
  requests: { cpu: 100m, memory: 256Mi }
  limits:   { cpu: 400m, memory: 512Mi }

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true
