# Prod: SemVer-taggar (vX.Y.Z), stabilt
image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v0.1.8
  digest: "sha256:6e5147b29be75c67c22aab30340fb15d5b3bcc9ce000a2eb5b5e2001e4883fe6"
resources:
  requests: { cpu: 100m, memory: 256Mi }
  limits:   { cpu: 400m, memory: 512Mi }
  
ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true

alerts:
  enabled: true
  targetNamespace: electricity-prod

serviceMonitor:
  enabled: true
