# Dev: täta deploys, tag sätts av CI (dev-<sha>)
image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-001cd58
  digest: "sha256:0944dfd72641c590b8049c1af895fdcec65fdaae4d9007daba8b9329f05b6287"

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

serviceMonitor:
  enabled: true
  additionalLabels:

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

