image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-e0177d9
  digest: "sha256:790b833f0355c70fa9165818104b2f3f4216f95cc83caadd83494031333b1cf4"

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits:   { cpu: 200m, memory: 256Mi }

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false

