# Dev: täta deploys, tag sätts av CI (dev-<sha>)
image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-fbd000e
  digest: "sha256:2e33af6c2b6dd29552de27cb1c2698376a00e2af607dcc2ebaf3d68ca7ac5453"

# Behåll basens portsättning (service.name/http, port/targetPort=8000)
# Om man vill överskrida specifikt för DEV, avkommentera nedan:
# service:
#   name: http
#   port: 8000
#   targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  # Om man vill ha gna limits i DEV
  # limits:
  #   cpu: 200m
  #   memory: 256Mi

# TODO: Slå på när du Prometheus Operator redo i klustret
serviceMonitor:
  enabled: false
  additionalLabels:

