# Dev: täta deploys, tag sätts av CI (dev-<sha>)
image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-087b87f
  digest: "sha256:cd0ed53902a7f0faa5d9fe067ff3036afa9892d9b1ad8ec669963b8dac00ab58"

# Behåll basens portsättning (service.name/http, port/targetPort=8000)
# Om man vill överskrida specifikt för DEV, avkommentera nedan:
# service:
#   name: http
#   port: 8000
#   targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  # Om man vill ha gna limits i DEV
  # limits:
  #   cpu: 200m
  #   memory: 256Mi

# TODO: Slå på när du Prometheus Operator redo i klustret
serviceMonitor:
  enabled: false
  additionalLabels:

